/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fuchao_ffmpegandroidplayer_VideoPlayer */

#ifndef _Included_com_fuchao_ffmpegandroidplayer_VideoPlayer
#define _Included_com_fuchao_ffmpegandroidplayer_VideoPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fuchao_ffmpegandroidplayer_VideoPlayer
 * Method:    init
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT jint JNICALL Java_com_fuchao_ffmpegandroidplayer_VideoPlayer_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_fuchao_ffmpegandroidplayer_VideoPlayer
 * Method:    play
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fuchao_ffmpegandroidplayer_VideoPlayer_play
  (JNIEnv *, jobject);

/*
 * Class:     com_fuchao_ffmpegandroidplayer_VideoPlayer
 * Method:    pause
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fuchao_ffmpegandroidplayer_VideoPlayer_pause
  (JNIEnv *, jobject);

/*
 * Class:     com_fuchao_ffmpegandroidplayer_VideoPlayer
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fuchao_ffmpegandroidplayer_VideoPlayer_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_fuchao_ffmpegandroidplayer_VideoPlayer
 * Method:    seek
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_fuchao_ffmpegandroidplayer_VideoPlayer_seek
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
